# Generated by Django 3.2.16 on 2024-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
