# Generated by Django 3.2.16 on 2024-02-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_reminder_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date',
            new_name='deadline',
        ),
    ]
