# Generated by Django 3.2.16 on 2024-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20240403_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paymentMethod',
            field=models.CharField(default='Cash', max_length=266),
        ),
    ]
