# Generated by Django 3.2.16 on 2024-04-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_expense_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
