# Generated by Django 3.2.16 on 2024-04-07 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20240407_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
