# Generated by Django 3.2.16 on 2024-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20240407_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='address',
            field=models.CharField(blank=True, max_length=1266, null=True),
        ),
    ]
